### ISSUE TITLE
issues needs to fix

### ISSUE THREAD

**Issue by Div-47** [hoc081098/flutter_google_places_hoc081098#22]
if user selected any predictions then predictions should be empty and the text field also should be empty. and give some customisation in the text field , on changed in the autocomplete.

**Comment by lepepper** [comment]
Issue- Flutter plugin : google_maps_webservice^0.0.20-nullsafety.5"  "fields" Attribute gives error

I am using this 
"google_maps_webservice^0.0.20-nullsafety.5" in flutter
& 
 flutter_google_places_hoc081098: ^1.0.1

Can some one please let me know, what I am  doing wrong here


Signature:
Future  getDetailsByPlaceId(
   String placeId, {
   String? sessionToken,
   List  fields = const [],
   String? language,
   String? region, }
   )

Here is how iam using it

      PlacesDetailsResponse detail =
          await _places.getDetailsByPlaceId(
              p.placeId.toString(),
              fields: ['name'],		// Commenting g out this line, woruld make it work, bt i need this attribute/property to save cost
              language: 'fr',
              region:"fr",
          );




Issue:
fields: ['name'] => this "fields" attribute keeps failing,
I have seen so many tutorials , all are suggesting the same way, 
but still it fails  with the below message



E/flutter ( 9854): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter ( 9854): #0      _$PlaceDetailsFromJson (package:google_maps_webservice/src/places.g.dart:138:31)
E/flutter ( 9854): #1      new PlaceDetails.fromJson (package:google_maps_webservice/src/places.dart:710:7)
E/flutter ( 9854): #2      _$PlacesDetailsResponseFromJson (package:google_maps_webservice/src/places.g.dart:294:26)
E/flutter ( 9854): #3      new PlacesDetailsResponse.fromJson (package:google_maps_webservice/src/places.dart:838:7)
E/flutter ( 9854): #4      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:528:29)
E/flutter ( 9854): #5      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:126:12)
E/flutter ( 9854): <asynchronous suspension>
E/flutter ( 9854): #6      _LocationPickerInitialState.goToPlace (package:myproj/screens/maps/initialOwnerLocationpicker.dart:149:11)
E/flutter ( 9854): <asynchronous suspension>

**Comment by hoc081098** [comment]
> Issue- Flutter plugin : google_maps_webservice^0.0.20-nullsafety.5"  "fields" Attribute gives error
> 
> I am using this 
> "google_maps_webservice^0.0.20-nullsafety.5" in flutter
> & 
>  flutter_google_places_hoc081098: ^1.0.1
> 
> Can some one please let me know, what I am  doing wrong here
> 
> 
> Signature:
> Future  getDetailsByPlaceId(
>    String placeId, {
>    String? sessionToken,
>    List  fields = const [],
>    String? language,
>    String? region, }
>    )
> 
> Here is how iam using it
> 
>       PlacesDetailsResponse detail =
>           await _places.getDetailsByPlaceId(
>               p.placeId.toString(),
>               fields: ['name'],		// Commenting g out this line, woruld make it work, bt i need this attribute/property to save cost
>               language: 'fr',
>               region:"fr",
>           );
> 
> 
> 
> 
> Issue:
> fields: ['name'] => this "fields" attribute keeps failing,
> I have seen so many tutorials , all are suggesting the same way, 
> but still it fails  with the below message
> 
> 
> 
> E/flutter ( 9854): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
> E/flutter ( 9854): #0      _$PlaceDetailsFromJson (package:google_maps_webservice/src/places.g.dart:138:31)
> E/flutter ( 9854): #1      new PlaceDetails.fromJson (package:google_maps_webservice/src/places.dart:710:7)
> E/flutter ( 9854): #2      _$PlacesDetailsResponseFromJson (package:google_maps_webservice/src/places.g.dart:294:26)
> E/flutter ( 9854): #3      new PlacesDetailsResponse.fromJson (package:google_maps_webservice/src/places.dart:838:7)
> E/flutter ( 9854): #4      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:528:29)
> E/flutter ( 9854): #5      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:126:12)
> E/flutter ( 9854): <asynchronous suspension>
> E/flutter ( 9854): #6      _LocationPickerInitialState.goToPlace (package:myproj/screens/maps/initialOwnerLocationpicker.dart:149:11)
> E/flutter ( 9854): <asynchronous suspension>

Thanks for report.

**Comment by lepepper** [comment]
Thanks for the response, 
If there is a mistake on our side, and any remedial measures, please let me know.

**Comment by hoc081098** [comment]
@lepepper I will look at it tomorrow :))

**Comment by lepepper** [comment]
just a additional info , which might help

The Below code works and generates a proper url, 
if the generated URL is opened in browser, the field attribute works

---Snip-----------
 String detail =
    _places.buildDetailsUrl(
        placeId: p?.placeId.toString(),
        //sessionToken: "sessionToken",
        fields: ['name','formatted_address'],
        region:"in",
        language: 'en'
    ) ;

---Snip-----------

    print (detail );


Also noticed one more minor anomaly in google_maps_webservice: ^0.0.20-nullsafety.5 package

google_maps_webservice
String buildDetailsUrl({
    String? placeId,

**Comment by lepepper** [comment]
Also noticed one more minor anomaly in google_maps_webservice: ^0.0.20-nullsafety.5 package


String buildDetailsUrl({
String? placeId,  --------------------->**this is of type String?**

Future<PlacesDetailsResponse> getDetailsByPlaceId(
    String placeId, { -------------------------------->  --------------------->**this is of type String**

**Comment by lepepper** [comment]
Hi

can you please fix this issue

**Comment by lepepper** [comment]
> @lepepper I will look at it tomorrow :))

Can you please fix the issue, or let is there something we are missing? 
please update

will be happy to buy you coffee :-)
